### PR TITLE
Adds imports in module decleration

### LINKED ISSUE #63: add info about imports in module declaration
when creating 3rd party modules declarations imports should be put inside, otherwise it will be treated as augmentation and show error
Example:
```ts
declare module "react-custom-scrollbars" {
    import * as React from "react";

    export interface positionValues {
    ...
```

### PR DESCRIPTION
**Pull request by arshadkazmi42**
Fixes #63 
-

### CODE REVIEW

**Comment by arshadkazmi42** [comment]
@piotrwitek I did rebase with master,
but semaphoreci is faling the build.
Its throwing this error
```
src/features/todos-typesafe/reducer.spec.ts:7:7 - error TS6133: 'completedTodo' is declared but its value is never read.
```
Looks like there is a declared value which is not getting used. Do want me to remove  it and update the PR or it something related to your changes?

**Comment by piotrwitek** [comment]
@arshadkazmi42 this was me sorry for that, I fix the build now, could you try again please?

**Comment by arshadkazmi42** [comment]
@piotrwitek Done with rebasing. Build is passing now.
There is one more change added to my PR after rebase
https://github.com/piotrwitek/react-redux-typescript-guide/pull/130/files#diff-04c6e90faac2675aa89e2176d2eec7d8R113

Can you check it once if its required

**Comment by piotrwitek** [comment]
Hey @arshadkazmi42, your branch history is somehow broken, you have many duplicated commits. I would advise to create a new branch from master HEAD and then cherry-pick only 2 commits original commits with your changes. then submit another PR or just clean up your branch with push force.
Let me know if something is not clear.

**Comment by arshadkazmi42** [comment]
Let me create a fresh PR from latest master.
I will close this PR.

**Pull request closed without merging**
