### PR TITLE
Remove redux#next reference

### PR DESCRIPTION
**Pull request by emp823**
The redux#next branch does not appear to exist any longer: [Redux Branches](https://github.com/reactjs/redux/branches)

### CODE REVIEW

**Comment by piotrwitek** [comment]
Hello @emp823 
Thanks for a heads-up and the PR, but it's not mergeable at the moment, because there is a auto-generation script that needs to be run.

If you'd like to become the contributor here's the guide: https://github.com/piotrwitek/react-redux-typescript-guide#contribution-guide

**Comment by emp823** [comment]
Whoops, thanks I'll redo this

**Comment by emp823** [comment]
@piotrwitek ran the generate script

Noticed the line concerning `Join the chat at https://gitter.im/react-redux-typescript-guide/Lobby` changed as well but I think that was missing from the source docs.

Let me know if anything else needs to be changed and thanks.

**Comment by piotrwitek** [comment]
@emp823 hehe that's correct, I forgot to add it to the source myself ;)
But don't worry about it, I'll fix it in another PR.

**Comment by piotrwitek** [comment]
@emp823 it's fixed, please rebase

**Comment by emp823** [comment]
@piotrwitek made the changes

**Comment by piotrwitek** [comment]
@emp823 that's perfect! already merged, thanks a lot for contributing! :)

**Pull request merged**
